[package]
name = "abioticfactor-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
fastrand.workspace = true
serde.workspace = true
serde_json.workspace = true
parry3d-f64.workspace = true
parking_lot.workspace = true
modforge = { path = "../modforge" }

[lints]
workspace = true
