//! Wild West Miner RPG mod. Rust cdylib loaded by Unityforge.Shim.
//!
//! Bootstrap path:
//! 1. BepInEx loads `Unityforge.Shim.dll` into the WWM process.
//! 2. The shim's `Awake` locates `wwm_rpg.unityforge.dll`,
//!    `LoadLibrary`s it, and calls `unityforge_init(bridge)`.
//! 3. `unityforge_init` is generated by the `unityforge_mod!`
//!    macro below; it stores the bridge, then calls `on_init`.
//! 4. `on_init` registers the framework's generic ops, the
//!    Unity-side selectors, and this mod's skill catalog +
//!    Harmony hooks.
//! 5. The shim's MonoBehaviour.Update calls `unityforge_tick`
//!    every frame, which drains the main-thread queue.

mod jump;
mod skills;

use unityforge::ModDef;

static MOD_INFO: ModDef = ModDef {
    name: "WildWestMinerRpg",
    version: "0.1.0",
    http_port: 17172,
    on_init: Some(on_init),
    on_tick: None,
    on_shutdown: Some(on_shutdown),
    tabs: &[
        modforge::ui::TabDef {
            name: "RPG",
            render: skills::render_tab,
        },
    ],
};

unityforge::unityforge_mod!(MOD_INFO);

fn on_init() {
    // Generic primitive ops (ping, walk_class, inspect_object,
    // read_field, write_field, invoke_method, list_ops, ...).
    unityforge::ops::register_builtins();

    // Selector resolvers (singleton:, static_instance:, class:,
    // first_class:, handle:).
    unityforge::selector::register_builtins();

    // RPG catalog + Harmony hooks.
    skills::install();

    // Spacebar -> jump. WWM has no native jump; this adds one
    // by Translate-ing the player +3m on press. Gravity does
    // the descent.
    jump::install();

    unityforge::mono::log(
        unityforge::mono::LogLevel::Info,
        "wwm-rpg: ready (ops + selectors + skills installed)",
    );
}

fn on_shutdown() {
    unityforge::mono::log(
        unityforge::mono::LogLevel::Info,
        "wwm-rpg: shutdown",
    );
}
