"""Dump ~15 lines of context around every call site of every unmapped
gene in FUN_14009f680. Output is a markdown doc humans can read to
hand-assign each gene to its slot(s).
"""
import re
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent
GENES_XML = ROOT / "../docs/vanilla-genes.xml"
ENGINE_C = ROOT / "decompiled/funcs/14009/14009f680_FUN_14009f680.c"
OUT = ROOT / "../docs/GENE-CONTEXT-UNMAPPED.md"

UNMAPPED = set("""AGOUTI ALT_BLUE ARM_STRETCH ARM_STRETCH2 ASPECT BASE_BLACK BASE_BROWN
BASE_CREAM BASE_GREEN BASE_RED BIPED BONES BONES2 BRAIN_SPASTIC BUGEYE CHEST_SMALL
ELBOW_RANGE EYEBOX_SIZE EYE_HUE FLU_IMMUNITY FOOT_BACKWARDS FOOT_IS_CIRCLE
FOOT_IS_HOOF GREEN_KNOCKOUT HAS_ANTLERS HAS_ELBOW HAS_KNEE HAS_MOUTH HAS_PUPIL
HAT_EXISTS HAT_POM_IS_LID HEAD_ASPECT HEAD_CHIMERA HEAD_JOINTED HEAD_SHRUNK
HEAD_SIZE HEAD_SQUARE HEAD_THICK_SKULL HIGH_INTELLECT KNEE_MAX KNEE_MIN
LEG_IS_CIRCLE LEG_PENCIL LEG_THRUST_BACK LIMP LOCO_SYNC NARCOLEPSY NECK_ONTOP
NECK_SLOUCH NOSE_HUE NOSE_INNY NOSE_SIZE POM_USECOLOR RAMPAGE SIZE SKINNY
SKIN_HANDS SKIN_HEAD SKIN_HUE SKIN_HUE2 SPINAL_LOCO SPOT_YELLOW SWAP_ALT_SPOT
SWAP_BASE_SPOT TAIL_ALT TAIL_BOTTOM TAIL_SEGMENTS TAIL_WAG TEETH_UPPER
TEETH_UPPER2 UPARM_GOOFY UPARM_Y WHITE WHITE_IS_LETHAL""".split())

CALL_RE = re.compile(
    r"FUN_1400a5(?:d20|e00)\s*\(\s*\w+\s*,\s*(0x[0-9a-fA-F]+|\d+)\s*\)"
)
SLOT_WRITE_RE = re.compile(r"param_1\[\s*(0x[0-9a-fA-F]+|\d+)\s*\]\s*=")
PTR_WRITE_RE = re.compile(r"\*\s*([a-zA-Z_]\w*)\s*=")
PTR_ALIAS_RE = re.compile(r"^\s*([a-zA-Z_]\w*)\s*=\s*param_1\s*\+\s*(0x[0-9a-fA-F]+|\d+)")
BYTE_WRITE_RE = re.compile(r"\(\s*param_1\s*\+\s*(0x[0-9a-fA-F]+|\d+)\s*\)\s*=")


def parse_num(s):
    return int(s, 16) if s.lower().startswith("0x") else int(s)


def main():
    names = [g.get("name", "?") for g in ET.fromstring(GENES_XML.read_text(encoding="utf-8")).findall("gene")]
    name_to_idx = {n: i for i, n in enumerate(names)}
    lines = ENGINE_C.read_text(encoding="utf-8").splitlines()

    # First pass: collect pointer aliases globally (pfVarN = param_1 + N)
    ptr_alias = {}
    for line in lines:
        m = PTR_ALIAS_RE.search(line)
        if m:
            ptr_alias[m.group(1)] = parse_num(m.group(2))

    out = ["# Gene context dump (unmapped genes)\n",
           "Each unmapped gene's call sites in `FUN_14009f680` with ~10 lines\n",
           "of context. Use this to hand-assign slot(s) per gene.\n",
           "Generated by `research/extract-gene-context.py`.\n"]

    for name in sorted(UNMAPPED):
        if name not in name_to_idx:
            continue
        idx = name_to_idx[name]
        out.append(f"\n---\n\n## {idx}  `{name}`\n")
        # find call sites
        sites = []
        for i, line in enumerate(lines):
            for m in CALL_RE.finditer(line):
                if parse_num(m.group(1)) == idx:
                    sites.append(i)
                    break
        if not sites:
            out.append("_no calls in FUN_14009f680 — gene is dead._\n")
            continue
        for ln in sites:
            out.append(f"\n### L{ln+1}\n\n```c\n")
            lo = max(0, ln - 2)
            hi = min(len(lines), ln + 18)
            for j in range(lo, hi):
                marker = ">>>" if j == ln else "   "
                out.append(f"{marker} {j+1:5d}  {lines[j].rstrip()}\n")
            out.append("```\n")
            # Look-ahead: any slot writes in next 25 lines
            slot_writes = []
            for j in range(ln, min(len(lines), ln + 25)):
                m = SLOT_WRITE_RE.search(lines[j])
                if m:
                    slot_writes.append((j+1, parse_num(m.group(1)), lines[j].strip()[:120]))
                m = BYTE_WRITE_RE.search(lines[j])
                if m:
                    byte_off = parse_num(m.group(1))
                    slot_writes.append((j+1, byte_off // 4, f"BYTE@0x{byte_off:x}: " + lines[j].strip()[:100]))
                m = PTR_WRITE_RE.search(lines[j])
                if m and m.group(1) in ptr_alias:
                    slot_writes.append((j+1, ptr_alias[m.group(1)], f"PTR {m.group(1)}: " + lines[j].strip()[:100]))
            if slot_writes:
                out.append("\nNearby slot writes:\n\n")
                for sln, slot, txt in slot_writes:
                    out.append(f"- L{sln}: slot {slot}  ({txt})\n")

    OUT.write_text("".join(out), encoding="utf-8")
    print(f"wrote {OUT}  ({len(UNMAPPED)} genes)")


if __name__ == "__main__":
    main()
