//! The Boss Gangsters Nightlife mod. Rust cdylib loaded by
//! Unityforge.Shim.
//!
//! Bootstrap path:
//! 1. BepInEx loads `Unityforge.Shim.dll` into the game process.
//! 2. The shim's `Awake` locates `bossgangsters_mod.unityforge.dll`,
//!    `LoadLibrary`s it, and calls `unityforge_init(bridge)`.
//! 3. `unityforge_init` is generated by the `unityforge_mod!`
//!    macro below; it stores the bridge, then calls `on_init`.
//! 4. `on_init` registers the framework's generic ops and the
//!    Unity-side selectors.
//! 5. The shim's MonoBehaviour.Update calls `unityforge_tick`
//!    every frame, which drains the main-thread queue.
//!
//! Game facts (verified 2026-08-29):
//! - Exe: TheBossGangsters.exe, developer BefGames.
//! - Install: C:\Games\Steam\steamapps\common\The Boss Gangsters Nightlife
//! - Unity 6000.3.13f1, Mono scripting backend.
//! - No shipped mod loader; BepInEx 5.x x64 Mono installed by hand.

mod fight_speed;
mod food_regen;
mod hit_squads;
mod punching_bag;
mod skill_cap;

use unityforge::ModDef;

static MOD_INFO: ModDef = ModDef {
    name: "BossGangsters",
    version: "0.1.0",
    http_port: 17176,
    on_init: Some(on_init),
    on_tick: None,
    on_shutdown: Some(on_shutdown),
    tabs: &[],
};

unityforge::unityforge_mod!(MOD_INFO);

fn on_init() {
    // Generic primitive ops (ping, walk_class, inspect_object,
    // read_field, write_field, invoke_method, list_ops, ...).
    unityforge::ops::register_builtins();

    // Selector resolvers (singleton:, static_instance:, class:,
    // first_class:, handle:).
    unityforge::selector::register_builtins();

    // Raise the skill level cap from 10 to 100.
    skill_cap::install();

    // Hit the punching bag automatically on every prompt.
    punching_bag::install();

    // Fast food buys healing regen scaled by its price.
    food_regen::install();

    // Fight skill scales the player's movement speed.
    fight_speed::install();

    // Family hit squads that come for the player (hit_squad op).
    hit_squads::install();

    unityforge::mono::log(
        unityforge::mono::LogLevel::Info,
        "bossgangsters-mod: ready (ops + selectors installed)",
    );
}

fn on_shutdown() {
    unityforge::mono::log(
        unityforge::mono::LogLevel::Info,
        "bossgangsters-mod: shutdown",
    );
}
